trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: apiservicesacr
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package -Dmaven.test.skip=true'
- task: Docker@2
  displayName: Build and Push
  inputs:
    command: buildAndPush
    repository: spring-demo
    tags: latest
    
- task: KubernetesManifest@0
  displayName: Deploy to Kubernetes cluster
  inputs:
   kubernetesServiceConnection: apiservice-akscluster-default
   namespace: default
   action: deploy
   manifests: |
     $(Pipeline.Workspace)/manifests/deployment.yml
     $(Pipeline.Workspace)/manifests/service.yml
   imagePullSecrets: apiservicesacr1170c1a7-auth
   containers: apiservicesacr.azurecr.io/spring-demo:latest
