apiVersion: v1
kind: Service
metadata:
  name: spring-demo-service
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: http-port
      protocol: TCP
  selector:
    app: test-server
