apiVersion: v1
kind: Service
metadata:
    name: externalgetserviceinfoapidockercontainer-service
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: externalgetserviceinfoapidockercontainer
